
    drop table domain_one if exists;

    create table domain_one (
        id bigint generated by default as identity,
        version bigint not null,
        action varchar(255) not null,
        controller varchar(255) not null,
        primary key (id)
    );

    alter table domain_one 
        add constraint unique_action unique (controller, action);

    alter table domain_one 
        add constraint UK_68gabj3tgv6og4w1g9dh8evk unique (action);
